#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i "s/server_name _;/server_name _;\n\treturn 301 https:\/\/elviswangari.hashnode.dev\/;/" /etc/nginx/sites-available/default
sudo service nginx restart
