#!/usr/bin/env bash
#a script to install and configure nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo mkdir -p /var/www/html/redirect_me
echo "
server{
  listen 80;
  root /var/www/html;

  add_header X-Served-By "web-01"
  
  location / {
    try_files index.nginx-debian.html $uri/index.html $uri $uri/ $uri.html;
  }
  location /redirect_me {
    return 301 https://elviswangari.hashinode.dev;
  }

  error_page 404 /404.html;
  location /404.html {
    root /var/www/html;
    internal;
  }
}
" > /etc/nginx/sites-available/default
