#!/usr/bin/env bash
#a script to install and configure a load balancer (haproxy)
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo echo "ENABLED=1" > /etc/default/haproxy
sudo echo "
defaults
  mode http
  timeout client 10000ms
  timeout connect 3000ms
  timeout server 10000ms
frontend elviso-front
  bind *:80
  option forwardfor
  default_backend elviso-back

backend elviso-back
  balance roundrobin
  server 119436-web-01 100.26.177.25:80 check
  server 119436-web-02 52.23.213.63:80 check
" > /etc/haproxy/haproxy.cfg
sudo service haproxy restart
